//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionXDuration
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> TestXQuestionId { get; set; }
        public Nullable<int> RequestTime { get; set; }
        public Nullable<int> LeaveTime { get; set; }
        public Nullable<int> AnsweredTime { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual TestXQuestion TestXQuestion { get; set; }
    }
}
